- README.md
- package.json
This provides two things:
1. build as a pre-step to running
2. allow for additional configuration to JPM via `npm config`
> Build: some enhancements to the run scripts

- package.json
This does a couple of things:
* enhances `package` to generate the name from the `package.json` fields
* fixes `lint` to cover all of the JavaScript sources
* fixes `clean` to not delete all of `/node_modules` (otherwise `package` can fail)
* added `distclean` to get rid of **EVERYTHING** not trackable
This does not address issues building on Windows, which is a little more involved.
> build: fixes/enhancements to npm build scripts

- webpack.config.js
This switches us to opt-in for copying to dist. That way, we don't
accidentally copy over JS files that are already bundled by WebPack (this was
happening for l10n.js).
> Don't copy extra JS files to the dist dir

- README.md
- jpm-prefs.json
- package.json
Fixes #38 
This adds the two prefs that a new profile would need to actually load our extension now (legacy, unsigned) and pass them to jpm to run.
> Fix JPM so a profile can run legacy, unsigned extension

- src/webextension/manage/components/app.css
- src/webextension/manage/components/itemDetails.css
- src/webextension/manage/components/itemDetails.js
- src/webextension/manage/containers/currentItem.js
- src/webextension/manage/en-US.ftl
- test/manage/components/app-test.js
- test/manage/components/item-test.js
- test/manage/components/itemDetails-test.js
- test/manage/components/itemList-test.js
- test/manage/containers/addItem-test.js
- test/manage/containers/allItems-test.js
- test/manage/containers/currentItem-test.js
- test/manage/mock-redux-state.js
- test/mock-l10n.js
- test/setup.js
This PR rewrites a bunch of the logic in `<CurrentItem/>` so that we don't have the same conditionals all over. Hopefully it'll be more maintainable now. I also added tests for `<CurrentItem/>` plus one case I missed earlier for `<ItemDetails/>`.
Resolves #48.
> Rewrite the <CurrentItem/> container

- package-lock.json
- package.json
- src/webextension/background/datastore.js
- src/webextension/background/index.js
- src/webextension/background/messagePorts.js
- src/webextension/manage/index.js
- src/webextension/manage/messagePorts.js
- src/webextension/manage/reducers.js
- test/.eslintrc.json
- test/background/messagePorts-test.js
- test/manage/actions-test.js
- test/manage/components/app-test.js
- test/manage/components/item-test.js
- test/manage/components/itemDetails-test.js
- test/manage/components/itemList-test.js
- test/manage/containers/addItem-test.js
- test/manage/containers/allItems-test.js
- test/manage/containers/currentItem-test.js
- test/manage/messagePorts-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
- test/mock-l10n.js
- test/setup.js
Note: this PR is based on #55, so ignore the first 4 commits here.
This adds tests for the Redux-only bits (actions and reducers), plus fixes lint issues in `test/`. This brings us to 67% coverage (by statement).
> Add tests for Redux-specific bits

- src/webextension/background/datastore.js
This change works the same while `lockbox-datastore` follows CommonJS or if (when?) it switches to ES6 modules.
> import all exported DataStore symbols

- README.md
This is just a little commit to use the same icon style for codecov (instead of the square-corner one we had previously). I also put the URLs at the bottom of the README so that it's a little more human-readable.
> Use a consistently-styled codecov icon

- docs/CODEOWNERS
I'm in a documentation mood.
This will automatically add the matching code owner(s) to PR reviews (later rules take precedence): https://help.github.com/articles/about-codeowners/
> Quick draft of codeowners for reviews

- src/webextension/manifest.json.tpl
Just noticed this after #62 landed. We should use the templated add-on ID here.
> Use the "id" property from package.json in our webextension manifest

- .eslintrc.js
- src/webextension/common.js
- src/webextension/locales/en-US/manage.ftl
- src/webextension/manage/actions.js
- src/webextension/manage/components/app.js
- src/webextension/manage/components/item-list.js
- src/webextension/manage/components/item.css
- src/webextension/manage/components/item.js
- src/webextension/manage/containers/add-item.js
- src/webextension/manage/containers/all-items.js
- src/webextension/manage/containers/current-item.js
- src/webextension/manage/containers/item-filter.js
- src/webextension/manage/filter.js
- src/webextension/manage/reducers.js
- src/webextension/widgets/filter-input.css
- src/webextension/widgets/filter-input.js
- test/background/message-ports-test.js
- test/common.js
- test/manage/actions-test.js
- test/manage/components/item-list-test.js
- test/manage/components/item-test.js
- test/manage/containers/all-items-test.js
- test/manage/containers/item-filter-test.js
- test/manage/filter-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
- test/widgets-test.js
This PR adds usernames to the summary list on the left and a filter that searches over the item's title and username (it splits the query on spaces and case-insensitively searches for each word individually for now).
This could still use some improvements, although it might be good enough to land already. Some stuff we should resolve (eventually) though:
* It can be confusing if the currently-selected item is filtered out; not sure what the best thing to do here is. Maybe deselect it?
* Maybe use something like Redux Forms?
* The styling of the search widget could use improvement.
> Add a filter to search for items

- src/webextension/manage/components/app.css
- src/webextension/manage/components/app.js
- src/webextension/manage/components/item-details.js
- src/webextension/manage/components/item-list.js
- src/webextension/manage/components/item-summary.css
- src/webextension/manage/components/item-summary.js
- src/webextension/manage/components/item.css
- src/webextension/manage/containers/all-items.js
- src/webextension/manage/reducers.js
- src/webextension/widgets/scrolling-list.css
- src/webextension/widgets/scrolling-list.js
- test/manage/components/item-list-test.js
- test/manage/components/item-summary-test.js
- test/manage/containers/all-items-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
- test/widgets-test.js
(Note: ignore the first 4 commits since they're in other PRs.)
This adds a generic `<ScrollingList/>` widget that we can use for our left-hand pane. It also adds keyboard accessibility to the list so users *should* be able to navigate the entire UI without touching their mouse.
> Create a scrollable, keyboard-accessible list

- package.json
This _should_ fix the breaking Jenkins build reported:
https://bugzilla.mozilla.org/show_bug.cgi?id=1401740
I will spare you from the results of blame here...
> Fix CASE sensitivity of cross-env command

- src/webextension/locales/en-US/manage.ftl
- src/webextension/manage/actions.js
- src/webextension/manage/common.js
- src/webextension/manage/components/edit-item-details.js
- src/webextension/manage/components/item-details.css
- src/webextension/manage/components/item-details.js
- src/webextension/manage/containers/all-items.js
- src/webextension/manage/containers/current-item.js
- src/webextension/manage/reducers.js
- src/webextension/widgets/input.js
- test/manage/actions-test.js
- test/manage/components/edit-item-details-test.js
- test/manage/containers/all-items-test.js
- test/manage/containers/current-item-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
The plan here is to change the item details so that we're not *always* editing them. From the "view" mode, you can click Edit or Delete, and then in "edit" mode, you can edit the fields, Save, or Cancel.
This will also make auto-focusing the first form field in the editor easier, since it won't interrupt you when navigating through the list of items. Finally, I added a "new item" placeholder in the item list, since I think that should make it clearer what's going on for users.
> Add a view mode for the item details

- .gitignore
- docs/releases.md
- package.json
- webpack.config.babel.js
This way pipeline scripts looking for a package.json (addon) _or_ manifest.json (WebExtension) find what they're looking for (Test Pilot signing)
And switch to using jpm to build the xpi since it does what we need and we already have it, so no need for a zip dependency
Related to #25 #26 
---
Once this merges I'll attempt another build on `production` and check the Jenkins result
> Output addon.env at build for Jenkins pipeline

- package-lock.json
- package.json
Turns out hyphens don't meet Toolkit version format spec
https://developer.mozilla.org/en-US/docs/Toolkit_version_format
And I want to confirm bumping the version then properly updates the `updates.json` hosted by Test Pilot and the browser does then fetch and update the addon.
If this all works, this helps finish up #26 🎉
> Bump version to 0.1.0pre1

- .eslintignore
Builds on tags run `npm run package` after codecov has run (to build the XPI and add it to GitHub Releases).
But package runs eslint. And eslint then runs against the "coverage" directory?
https://travis-ci.org/mozilla-lockbox/lockbox-extension/builds/284306037#L4257
Would this change to ignore prevent all those warnings? ☝️
> Ignore coverage to prevent CI warnings on report

- package-lock.json
- package.json
- src/install.rdf.ejs
- src/webextension/manifest.json.tpl
Long story short, @jimporter was right: https://github.com/mozilla-lockbox/lockbox-extension/pull/62#pullrequestreview-64110542
We definitely need the `updates.json` to live in install.rdf for our non-WebExtension extension. Whoops.
Tested and confirmed locally that the updates screen does attempt to check the remote `updates.json` whereas it is definitely _not_ doing that without this change.
Sorry for the extra noise/hassle here. 😔
> Move updateURL to install.rdf so updates are actually checked

- .babelrc
- jpm-prefs.json
- package-lock.json
- package.json
- src/bootstrap.js
- src/webextension/background/browser-action.js
- src/webextension/background/message-ports.js
- src/webextension/background/telemetry.js
- src/webextension/telemetry.js
- test/background/browser-action-test.js
- test/background/message-ports-test.js
- test/background/telemetry-test.js
- test/bootstrap-test.js
- test/setup.js
- test/telemetry-test.js
(Only the last commit is relevant.)
@linuxwolf This is a rough sketch of what I'm thinking about for Telemetry. The goal is to have a simple API that looks like the XPCOM Telemetry API, since that should hopefully make it easy to convert to WebExtension-based Telemetry if/when we get it.
Some extra stuff that might be worth doing:
* Defining our events in a separate JSON file?
* Making a similar API for our background script events? This might make sender-side error-detection easier.
> Add telemetry

- src/bootstrap.js
- src/webextension/background/browser-action.js
- src/webextension/background/datastore.js
- src/webextension/background/message-ports.js
- src/webextension/background/telemetry.js
- src/webextension/firstrun/components/pages.js
- src/webextension/firstrun/index.js
- src/webextension/manage/actions.js
- src/webextension/manage/components/send-feedback.js
- src/webextension/manage/containers/add-item.js
- src/webextension/manage/index.js
- src/webextension/popup/unlock/index.js
- src/webextension/telemetry.js
- test/background/message-ports-test.js
- test/background/telemetry-test.js
- test/bootstrap-test.js
- test/telemetry-test.js
As discussed on Slack. Here's a quick fix that just makes our telemetry category versioned. This will break the other telemetry PR, so I'll land this after and fix stuff up myself.
> Fix telemetry event re-registration in the middle of an existing Firefox session

- src/webextension/locales/en-US/manage.ftl
Fixes #222 
In FTL, multiline translations must currently be indented by at least one space, including the closing `}` in select expressions.
> Fix indentation in FTL files

- src/bootstrap.js
- test/bootstrap-test.js
- test/mocks/xpcom.js
Note that this only applies to *new* installs of Lockbox, so existing users will want to uninstall Lockbox, restart Firefox, and reinstall. This is slightly inconvenient, but shouldn't be a problem in the long term.
> Disable the Firefox built-in password manager on install; resolves #184

- src/webextension/firstrun/components/master-password-setup.js
- test/bootstrap-test.js
- test/firstrun/components/master-password-setup-test.js
This fixes a minor issue where `<MasterPasswordSetup/>` wasn't always using controlled fields in React and adds a test to get us to that coveted 100% coverage. I also fixed an issue with clearing event listeners in the bootstrap.js tests.
> Improve first-run tests slightly

- src/bootstrap.js
- src/webextension/background/browser-action.js
- src/webextension/background/index.js
- src/webextension/background/views.js
- src/webextension/firstrun/components/master-password-setup.js
This just removes some logging and disables warnings for some other ones. I'm totally willing to debate which logging should be kept around, but I mainly went with just keeping error logging around.
With this patch, there are 0 eslint warnings, so maybe we could even make `console.log` usage throw an eslint error now. (It'll still warn on local builds, since we run lint in warn-only mode there.)
> Remove some unnecessary console.log calls

- src/webextension/.dir-locals.el
This makes my life easier (and presumably the lives of other emacs users). It should only trigger if you have js2-mode installed, but assumes you also have rjsx-mode installed.
> Use rjsx-mode for JS files in src/webextension

- README.md
- docs/index.md
- docs/release-notes.md
- package-lock.json
- package.json
Fast follow to #275, also fixes #270
Very minor point release that includes "this is a pre-release" language in the product and docs to remind any users this is subject to change and data may not be retained.
@sandysage I took a quick pass assuming this is what you'd want to say and how to say it. Please feel free to make any other edits directly to this branch.
Once approved by @mozilla-lockbox/product-integrity and @mozilla-lockbox/engineering and @sandysage we can merge to master, along with #275 and then create PR to merge master into production (thus creating the point release).
> Pre-release notes to include and push in 0.1.1-alpha1

- docs/releases.md
Resolves #195 
@linuxwolf @jimporter here are detailed instructions (just performed at 0.1.0-pre3, sans CHANGELOG) to publish a new version with a signed extension on Test Pilot and GitHub.
I showed @m8ttyB the actual Jenkins build/sign pipeline. The code is in a private repo and shared with all Test Pilot extensions, Jenkins/CloudBees with resulting output is behind a proxy requiring CloudOps access. Please let me know if it'd be helpful to walk through and demonstrate any of that. But you should be able to see the steps and results (building, signed, deployed) in IRC at `#testpilot-bots`.
I know this has already been reviewed and demonstrated, but do you have any other concerns? 
Anything in this process you'd like me to flesh out more?
Any questions? 😄 
Fixes #26
> Add release instructions

- src/webextension/locales/en-US/manage.ftl
- src/webextension/manage/components/item-list.js
- src/webextension/manage/components/item-summary.js
- src/webextension/manage/containers/all-items.js
- test/manage/components/item-summary-test.js
- test/manage/containers/all-items-test.js
I'd like to remove `withLocalization()`/`getString()` wherever possible. This removes it for the item list.
@stasm Is there a better way to handle the localization here? I want to have a fallback string when the user-defined string is empty, but the only way I could get to work was to pass the string's length in separately and select based on that.
> Remove usage of withLocalization()/getString() from the item list

- README.md
- docs/index.md
- docs/release-notes.md
- package-lock.json
- package.json
- src/webextension/firstrun/components/welcome.js
- src/webextension/locales/en-US/firstrun.ftl
I created the `0.1.1-alpha1-prod` branch and cherry-picked my two squashed commits since I don't want to pull _everything_ from `master` branch yet (dependency updates, empty sidebar).
This may be overly cautious but I think of it as our own version of doing an uplift and a point release.
Can I get a 👍 from @m8ttyB that we're still good for just these two commits (only) to go into production as a point release?
Once we hit the big green button ✅ this will be live and update any existing installations. Cool?
> Cherry pick and deploy 0.1.1-alpha1 to production

- webpack.config.babel.js
> Add locked favicon to firstrun page

- src/webextension/locales/en-US/manage.ftl
`$username` and `username` are very different!
> Fix bad translation of item summary username

- src/webextension/widgets/text-area.css
Resolves #256 again
Now the `text area` focus blue color matches the `input` fields. Consistency 👐
> Set text area focus blue to match input styles

- docs/install.md
Closes #274 by adding instructions on how to create a new profile, add it to your jpm config, and run it so it persists between runs. This way testers and developers can set up dummy data locally instead of having to do it every single time.
I've been doing this for a day or so. I know @linuxwolf said he was doing his own `cp -R` shenanigans to achieve roughly the same effect.
Either way, following these instructions mean my test profile opens with ~dozens of entries pre-loaded.
I know @jimporter also wanted to do #170 (a build config) but I wanted to quickly document this approach for those that want/need a good solution sooner.
> Add instructions on how to run dev builds with a profile

- mkdocs.yml
Fixes #366 
Depends on #51 (once populated, we should add it back)
> Remove empty "API Guide" from mkdocs

- src/webextension/list/containers/item-filter.js
- src/webextension/list/manage/containers/add-item.js
- src/webextension/widgets/button.css
- src/webextension/widgets/filter-input.js
- src/webextension/widgets/input.css
- src/webextension/widgets/password-input.js
- test/list/containers/item-filter-test.js
- test/list/manage/containers/add-item-test.js
- test/widgets/filter-input-test.js
Here's a quick version of disabling the filter when there are no items. No tests yet; I just wanted to see what people think of the UX, since the Photon specs don't appear to have anything about what disabled form fields should look like. We could also add a different placeholder string if we want, e.g. "Add some entries before filtering them" (that's terrible wording, but you get the idea).
> Disable the filter when there are no items; resolves #324

- docs/index.md
- docs/metrics.md
- src/webextension/firstrun/components/intro.js
- src/webextension/list/manage/components/account-linked.css
- src/webextension/list/manage/components/link-account.css
- src/webextension/list/manage/containers/open-faq.css
- src/webextension/list/manage/containers/open-faq.js
- src/webextension/locales/en-US/firstrun.ftl
- src/webextension/locales/en-US/list.ftl
- src/webextension/widgets/toolbar.css
- test/integration/pages/base.py
This is a quick branch with minor fixes from another "once over".
> Minor fixes before release

- docs/index.md
This was causing a 404 on the https://mozilla-lockbox.github.io/lockbox-extension/ site which was causing a bunch of other odd results from my link checker.
> Fix feedback link on docs/index

- test/integration/pages/home.py
- test/integration/pages/util/util.py
Fixes: #398
I have the ```munged_class_name``` function throw a ```ValueError``` if the requested class name is not found in the dictionary.
In doing this I found an incorrectly named class so I fixed that too.
> Added error handling to class name munger.

- tox.ini
> Allow running integration tests on Python 3.* instead of just 3.6

- docs/release-notes.md
- docs/releases.md
I hadn't finished publishing the update to the release process wherein we create a PR for a release (comparing `production` ◀️ `master`) such as the one here: https://github.com/mozilla-lockbox/lockbox-extension/pull/408
This update captures the step. @linuxwolf @jimporter for future releases is this instruction clear? Anything to add or change before merging?
> Release docs update

- src/webextension/background/browser-action.js
- src/webextension/background/datastore.js
- src/webextension/background/message-ports.js
Resolves #435 
Moves the `DEFAULT_APP_KEY` out of [datastore](/mozilla-lockbox/lockbox-datastore) to here.  This can land before or at the same time as the fix for mozilla-lockbox/lockbox-datastore#68.
Doing more requires a comprehensive solution to #426, and that's a much larger changeset than I think we're ready for.
> explicitly use guest-mode app key

- package.json
Adds "integration" to the package.json scripts, in order to run `tox`-based integration tests, with prerequisites.
> add integration test script runner

- src/webextension/widgets/scrolling-list.js
- test/unit/list/components/item-list-test.js
- test/unit/list/manage/containers/all-items-test.js
- test/unit/list/popup/containers/all-items-test.js
- test/unit/widgets/scrolling-list-test.js
This resolves - in a roundabout way - an issue with clicking the "new item" placeholder entry in the item list causing the editor widget to go away. It resolves a comment in #414.
Also note: this fixes the bug, but this was caused by a few bugs working together to screw everything up. The code for our Redux reducers is badong and I want to fix it (see #297).
> Don't fire an onChange event from <ScrollingList/> if the new item is already selected

- src/webextension/list/components/item-list.css
- src/webextension/list/components/item-list.js
- src/webextension/list/components/item-summary.css
- src/webextension/list/manage/containers/all-items.css
- src/webextension/list/manage/containers/all-items.js
- src/webextension/widgets/scrolling-list.css
- src/webextension/widgets/scrolling-list.js
This improves the styling for the item list, especially where the styles are defined. Notable bits:
* `border-right` (now `border-inline-end` for RTL support) is only defined for the management UI, so it won't hurt the doorhanger
* Right border is now always shown, since the "no right border" thing didn't work great when we had a scrollbar. (Todo: we should probably talk to the Photon design team about whether overlay scrollbars should be a Photon thing.)
* Borders are 1px now (Zeplin shows them as 0.5px, but that's because it's a border on all sides, and we just do bottom/right.
* Focus state is improved, and should follow @changecourse's visual suggestions. We can (possibly should) continue to look at this to decide what we can do to improve it further.
> Improve selected/focus state for the item list; resolves #414

- src/webextension/list/manage/components/app.css
Fixes #530 
I hate CSS. This mostly reverts the app.css changes from the dropdown patch but makes the main panel scroll if it overflows. Now, the <body> can never scroll because that would screw up clicking out of the dropdown. (This means that the minimum height for the management tab is something around 100px; anything less will cut stuff off.)
Note: I probably won't have much time to follow up on this since I am technically OoO now.
> Fix scrolling in management view

- package-lock.json
- package.json
- src/bootstrap.js
- test/unit/mocks/xpcom.js
This both pins us to `eslint-plugin-mozilla` version 0.6.0 and ignores future updates (for a bit).  It appears this plugin is broken (and some out-of-band follow up on that is needed), but this prevents some extraneous noise.
> pin and ignore to eslint-plugin-mozilla@0.6.0

- src/webextension/background/accounts/index.js
- src/webextension/background/browser-action.js
- src/webextension/background/datastore.js
- src/webextension/background/index.js
- src/webextension/background/message-ports.js
- test/unit/background/accounts-test.js
Fixes #568 
The referenced failure is due to browser storage only applied if an account was stored, but not when starting fresh.  This takes steps to ensure the storage is applied whenever `loadAccount()` (which is called by `openAccount()` succeeds.
> Ensure FxA account is stored always

- src/webextension/list/containers/item-filter.js
- src/webextension/list/manage/components/app.js
- src/webextension/list/popup/components/app.js
- src/webextension/list/popup/components/item-list-panel.js
- src/webextension/list/popup/containers/current-selection.js
- src/webextension/widgets/filter-input.js
- test/unit/list/manage/components/app-test.js
- test/unit/list/popup/components/app-test.js
- test/unit/widgets/filter-input-test.js
This PR auto-focuses the filter input boxes, but *only* when the entire page loads (using `autoFocus` will trigger a focus change any time the component is mounted, which has some bad UX on the doorhanger).
> Automatically focus the filter input when the page loads; resolves #573

- .travis.yml
We use pip install for mkdocs on the deploy stage for master
[Tornado 5.0](http://www.tornadoweb.org/en/latest/releases/v5.0.0.html) was released today which dropped support for older python versions.
I _think_ this will fix the PR build (that includes deploy) stage. Will wait and see if green. ✅
> Require python 3.6 in deploy stage so pip can install tornado

- .travis.yml
This is really a "PR to start a discussion" around a _hopefully_ 🤞 quick win to speed up our branch and PR builds: use Travis CI's caching to store `node_modules` ([read more on their blog](https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/) and [in the docs](https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches))
tldr: they will package up the `node_modules` directory and put it in S3, then pull it back down, per-branch and PR. If anything in the code changes the results, they get the updates and store that.
In some quick tests on my fork [seen here](https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches) I was able to shave off about ~1 minute per test during the `npm install` step (instead it just pulls down the assets and …
> Speed up branch and PR builds with Travis CI caching

- .travis.yml
I think I made a dumb mistake at #613 and "required" python in the wrong way. Right now master deploys are skipping the pages deploy because this is in "on" (check if its in the runtime vs just set the runtime).
> Move python runtime for deploy stage out of 'on' requirement

- src/webextension/common.js
- src/webextension/list/components/item-list.js
- src/webextension/list/components/item-summary.js
- src/webextension/list/containers/item-filter.js
- src/webextension/list/manage/components/account-summary.js
- src/webextension/list/manage/components/edit-item-details.js
- src/webextension/widgets/button.js
- src/webextension/widgets/copy-to-clipboard-button.js
- src/webextension/widgets/dialog-box.js
- src/webextension/widgets/field-text.js
- src/webextension/widgets/filter-input.js
- src/webextension/widgets/input.js
- src/webextension/widgets/label-text.js
- src/webextension/widgets/link.js
- src/webextension/widgets/panel.js
- src/webextension/widgets/password-input.js
- src/webextension/widgets/scrolling-list.js
- src/webextension/widgets/stack.js
- src/webextension/widgets/text-area.js
- src/webextension/widgets/toolbar.js
- test/unit/mocks/l10n.js
This is effectively a simplified version of the npm `classnames` package. This commit also moves `{...props}` to the beginning of our list of applied props so that it's no longer possible to accidentally overwrite internal props.
This is a fairly big diff, but it's pretty simple, and should make it easier to apply our CSS class names. (I'm doing this now because I've been finding it an issue while working on the breadcrumbs PR.)
> Create a classNames() function to handle building className props more easily

- src/webextension/widgets/filter-input.js
- src/webextension/widgets/input.css
- test/unit/widgets/filter-input-test.js
Fixes #622 
This changes the styles and checks the state so that the clear ❌ button does not show on the search/filter input until there is actually text in the field.
@jimporter I think this is the right way to check both for the input value _and_ inherit the entire form's `disabled` prop...
> Hide "clear" button on filter when there is no input

- docs/CODEOWNERS
@jimporter @m8ttyB As proposed and discussed via email.
Here's how I believe you'd want it to look in GitHub reviews, themselves...
> Updated CODEOWNERS to explicitly assign integration test ownership

- .travis.yml
- requirements/tests.txt
- test/integration/README.md
- test/integration/tests/test_doorhanger.py
Closes #744 
Bumps up all various testing dependencies
Adds xfail on the doorhanger because something in Firefox seems to have changed in how the content within the doorhanger is made available (I can't even seem to manually inspect the markup via Browser Toolbox anymore)
> Update dependencies and fix integration test failures
