mozilla-lockbox/lockbox-extension

- docs/index.md
- mkdocs.yml
if we do this then we can set up the repo to use GitHub Pages, and then `mkdocs gh-deploy` to deploy to the `gh-pages` branch
> set up mkdocs

- package-lock.json
- package.json
- src/webextension/background.js
- webpack.config.js
starts the road to addressing #30
> trivial include of 🔒📦 DataStore

- .eslintrc.json
- package-lock.json
- package.json
- src/webextension/en-US.ftl
- src/webextension/l10n.js
- src/webextension/manage.js
- webpack.config.js
> Support localization via fluent.js; resolves #18

- .eslintrc.json
- package-lock.json
- package.json
- src/webextension/l10n.js
- src/webextension/manage.js
- src/webextension/redux.js
Still not 100% sure about this, but it's a start. I'm still looking into whether it would make more sense to have the Redux store live in the background scripts.
resolves #24
> Support Redux; resolves #24

- .travis.yml
The issue points to configuring travis-ci to run tests however no tests have been written. We do however have `eslint`.  As a task to complete after issue #28 I suggest we include updating the `.travis.yml` file to execute tests.
If I've done this right, travis & node are new to me, this is the proper setup for a node project.
closes #29
> config travis ci run eslint; resolves #29

- package-lock.json
- package.json
- src/webextension/manage/components/app.css
- src/webextension/manage/components/app.js
- src/webextension/manage/components/entry.css
- src/webextension/manage/components/entry.js
- src/webextension/manage/components/entryDetails.css
- src/webextension/manage/components/entryDetails.js
- src/webextension/manage/components/entryList.css
- src/webextension/manage/components/entryList.js
- src/webextension/manage/containers/currentEntry.css
- src/webextension/manage/containers/currentEntry.js
- src/webextension/manage/index.html
- webpack.config.js
See <https://javascriptplayground.com/blog/2016/07/css-modules-webpack-react/>
for more details on how this works.
> Use modular CSS to style the management UI

- src/template.ejs
- src/webextension/manage/components/app.css
- src/webextension/manage/components/app.js
- src/webextension/manage/components/item.css
- src/webextension/manage/components/itemDetails.js
- src/webextension/manage/components/itemList.css
- src/webextension/manage/containers/addItem.js
- webpack.config.babel.js
@jimporter I wanted to quickly play around with CSS Grid and make some quick UI changes.
Are you okay with these style updates?
> Add some basic styles

- .codecov.yml
in codecov docs, false means off: https://docs.codecov.io/v4.3.6/docs/pull-request-comments
(waiting to make sure bot doesn't actually comment here)
> disable codecov commenting 

- src/webextension/background/datastore.js
- src/webextension/background/index.js
- src/webextension/background/message-ports.js
- test/background/message-ports-test.js
This is an attempt to work with `lockbox-datastore` in an asynchronous manner.
This is probably not the right way to do it, but it minimized the changes needed.
> Work with datastore asynchronously

- src/webextension/manage/components/item-details.js
- src/webextension/manage/containers/add-item.js
- src/webextension/widgets/button.js
- src/webextension/widgets/input.js
- test/widgets-test.js
What do you think of something like this to manage styling our widgets? Hopefully this will mean less micromanagement since our components will automatically ensure we use the correct styles.
> Add common widgets so we don't have to manually manage browser-style stuff

- src/webextension/common.js
- src/webextension/locales/en-US/manage.ftl
- src/webextension/manage/components/item-details.css
- src/webextension/manage/components/item-details.js
- src/webextension/manage/containers/current-item.js
- src/webextension/manage/filter.js
- src/webextension/widgets/input.css
- src/webextension/widgets/text-area.js
- test/background/message-ports-test.js
- test/manage/components/item-details-test.js
- test/manage/containers/current-item-test.js
- test/manage/filter-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
- test/widgets-test.js
This resolves #81 and is based on #83 (so ignore the first two commits).
> Add more fields to the management UI

- src/template.ejs
This now validates successfully and does not throw any console errors.
Fixes #101
> Add character encoding to manage HTML

- package-lock.json
- package.json
> Add node-zip to allow compression across environments

- src/webextension/manage/containers/all-items.js
- src/webextension/manage/containers/item-filter.js
- src/webextension/manage/filter.js
- src/webextension/manage/reducers.js
- test/manage/containers/all-items-test.js
- test/manage/containers/item-filter-test.js
- test/manage/filter-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
This is a small cleanup patch to ensure that the filter stays in sync with the Redux store.
> Make our <ItemFilter/> always display the current redux state of the filter

- package-lock.json
- package.json
Hopefully fixes #127 
@jimporter can you please test and run on your machine and confirm package works and the xpi loads ok for you? works on mine. 😁
> Replace node-zip with jpm for XPI packaging

- .eslintignore
- .gitignore
- package-lock.json
- package.json
- src/webextension/background/authorization.js
- src/webextension/background/browser-action.js
- src/webextension/background/index.js
- src/webextension/background/message-ports.js
- src/webextension/background/views.js
- src/webextension/firstrun/app.js
- src/webextension/firstrun/index.js
- src/webextension/firstrun/pages.js
- src/webextension/locales/en-US/popup.ftl
- src/webextension/manifest.json.tpl
- src/webextension/popup/unlock/index.css
- src/webextension/popup/unlock/index.js
- src/webextension/widgets/error-message.css
- src/webextension/widgets/error-message.js
- webpack.config.babel.js
Functionally the same as #116, but with less build failure
Closes #15 
Closes #16
> Prototyping Firsttime Run User Experience

- webpack.config.babel.js
Ref: https://github.com/mozilla-lockbox/lockbox-extension/pull/119#discussion_r142245365
> Fix Lockox typo

- src/webextension/background/authorization/configs.js
- src/webextension/background/authorization/index.js
- src/webextension/background/message-ports.js
- test/background/message-ports-test.js
This gets around some authentication/verification issues present in FxA's stable development environment.
> Use FxA latest development environment

- src/webextension/manage/components/app.css
> Ensure that the <ScrollingList/> scrolls when it has lots of items

- src/webextension/locales/en-US/manage.ftl
- src/webextension/locales/en-US/popup.ftl
Fast follow work from #154 related to #138 
~~(will rebase to get this cleaned up)~~
> Update UX strings

- docs/release-notes.md
- package-lock.json
- package.json
Because *of course* something is found ...
> Release 0.1.0-alpha1

- .travis.yml
Fixed #197 
This *should* fix the lack of documentation deployments.
> Fix travis linting errors

- .travis.yml
Fixes #197 
Tested on personal fork, _including_ the `branch: master` condition.
> Fix travis-ci deploy errors

- src/webextension/manage/components/edit-item-details.js
> Add maxLength to <EditItemDetails/>; resolves #103

- dir-list-webpack-plugin.js
- webpack.config.babel.js
> Ensure en-US is the default locale for dev builds; resolves #140

- src/webextension/manage/actions.js
- src/webextension/manage/components/edit-item-details.js
- src/webextension/manage/containers/all-items.js
- src/webextension/manage/containers/current-selection.js
- src/webextension/manage/containers/go-home.js
- src/webextension/manage/containers/item-filter.js
- src/webextension/manage/containers/modals.js
- src/webextension/manage/reducers.js
- test/manage/actions-test.js
- test/manage/components/edit-item-details-test.js
- test/manage/containers/all-items-test.js
- test/manage/containers/current-selection-test.js
- test/manage/containers/modals-test.js
- test/manage/mock-redux-state.js
- test/manage/reducers-test.js
- webpack.config.test.js
Resolves #162 
only the last 4 commits are unique to this PR.
> Fix modal dialogs

- src/webextension/manage/components/item-details.css
> Fix line wrapping in <ItemDetails/>; resolves #236

- package-lock.json
- package.json
- src/template.ejs
- src/webextension/firstrun/components/app.js
- src/webextension/locales/en-US/firstrun.ftl
- src/webextension/locales/en-US/manage.ftl
- src/webextension/manage/components/app.js
- webpack.config.babel.js
resolves #225 
Now our page titles are localized! vOv
The one minor downside is that we get a brief flash of the URL in the tab bar before our localizations load, but that's probably only noticeable if you're really paying attention.
> Localize page titles; resolves #225

- src/bootstrap.js
- test/bootstrap-test.js
- test/mocks/xpcom.js
Resolves #184
I'm smart. :/
The change should make it pretty obvious why this was broken...
> Fix resetting pref during uninstall

- src/webextension/locales/en-US/manage.ftl
- src/webextension/manage/components/item-list.css
- src/webextension/manage/components/item-list.js
- src/webextension/manage/containers/all-items.js
- test/manage/containers/all-items-test.js
This is split out from #168.
Fixes #165
> Empty list placeholder for sidebar

- src/webextension/firstrun/components/welcome.js
- src/webextension/locales/en-US/firstrun.ftl
Fixes #270 requested by @sandysage to explain features may change and data may not be retained between releases.
Here's how it looks (bold section in middle is new):
> Add a warning to first run introduction

- test/integration/README.md
I didn't think to look at tox itself so figure I'll write a love letter 💌 to some future individual who hits this same issue and isn't aware of it.
> Add instruction on how to run Tox recreate

- src/webextension/list/manage/containers/send-feedback.js
- src/webextension/widgets/link.css
- src/webextension/widgets/link.js
- test/widgets/link-test.js
Created as a separate PR for now to (hopefully, but possibly vainly) help track any changes necessary here without conflicting with ongoing work in #351 .
> add external link widget

- src/webextension/list/components/item-list.css
- src/webextension/list/manage/components/homepage.css
- src/webextension/list/manage/components/link-account.css
Some stuff I noticed while working on the dynamic sizing for the intro page.
> Fix sizing of various components in the manager to allow (very!) narrow screens

- .travis.yml
- src/webextension/background/browser-action.js
- webpack.config.babel.js
- webpack.config.test.js
we won't ever want to have it not enabled from here forward, so removing the code entirely
closed #377 
@jimporter is this all there is to it? or more to do? feel free to jump on the branch directly if I missed anything.
> Remove ENABLE_DOORHANGER code

- src/webextension/list/components/item-fields.css
- src/webextension/widgets/input.css
Addressing QA findings from @m8ttyB
> Fixes for QA findings before release

- docs/contributing.md
> update contributing URLs to point to right spots

- src/webextension/background/accounts/index.js
> Convert to Date.now() to avoid NaN

- .travis.yml
Potential fix for flakey travisci builds. 
To see the logic behind the changes checkout this [link](https://docs.travis-ci.com/user/reference/overview/)
> Trying sudo to use a VM.

- docs/telemetry-test-plan.md
> initial test plan for our telemetry work

- src/webextension/background/index.js
> Fix: guest mode does not work on restart

- docs/release-notes.md
- package-lock.json
- package.json
- src/webextension/background/accounts/index.js
- src/webextension/background/browser-action.js
- src/webextension/background/datastore.js
- src/webextension/background/index.js
- src/webextension/background/message-ports.js
- test/unit/background/accounts-test.js
Awaiting the following before removing (WIP):
> Publish 0.1.7-alpha1

- src/webextension/list/manage/components/intro-page.css
Resolves #478 
-Intro image shadow to Shadow 10
-Updated image border
-Defined line height for intro paragraphs
> Updating styling of 0 entries page to reflect designs

- docs/accessibility-test-plan.md
Added test plan from #497 to docs
> Add a11y test plan to docs

- src/webextension/list/components/item-fields.css
- src/webextension/list/components/item-fields.js
Resolves #480 
-~Modified password read only char code to match design~
-Fixed issue where bottom buttons would jump a bit from edit to view state
> Styling adjustments to align entry detail buttons during edit and view mode change

- src/webextension/list/containers/item-filter.js
- src/webextension/list/manage/components/app.js
- src/webextension/list/popup/components/app.js
- src/webextension/list/popup/index.js
- src/webextension/widgets/filter-input.js
- src/webextension/widgets/input.js
- src/webextension/widgets/text-area.js
- test/unit/chai-focus.js
- test/unit/common.js
- test/unit/list/containers/item-filter-test.js
- test/unit/list/manage/components/app-test.js
- test/unit/list/manage/components/edit-item-details-test.js
- test/unit/list/popup/components/app-test.js
- test/unit/widgets/button-stack-test.js
- test/unit/widgets/filter-input-test.js
- test/unit/widgets/input-test.js
- test/unit/widgets/text-area-test.js
Resolves #514 
I think this is close to done for an initial implementation of the URL prefilling. Perhaps I should move the stuff in `list/popup/index.js` to a separate file so I can write a unit test for it though...
> Prefill the URL in the doorhanger

- src/webextension/list/manage/components/item-details.css
Just noticed this; here's a fix.
> Fix the color of the horizontal line in the item details of the manager

- .travis.yml
See travis-ci/travis-ci#9312
Only discovered after fixing the accidental "skip" deploy last night at #630
> Downgrade Travis deploy script to fix pages deploy

- docs/metrics.md
- src/bootstrap.js
- src/webextension/background/telemetry.js
- test/unit/background/telemetry-test.js
> changes to metrics

- test/integration/pages/home.py
- test/integration/tests/test_account_creation.py
- test/integration/tests/test_doorhanger.py
- test/integration/tests/test_guest_mode.py
- test/integration/tests/test_lockbox.py
Resolves #663 
* A slight update to the existing door hanger test.
* Updates `new_entry()` to `create_new_entry()` which can take args.
* Begins to move away from the `munged_class_name()` helper and uses CSS selectors.
* Moves the remaining test cases into suites that match the canonical suites in TestRail.
> Improve DH integration tests and reorganize test suite

- docs/faqs.md
> Fix wrong docs becuase syncing is not currently supported

- docs/release-notes.md
- package-lock.json
- package.json
Work in progress to start preparing the release and notes.
> Prepare 0.1.9 release

- .travis.yml
- package-lock.json
- package.json
* Updates lockbox-datastore to 0.2.1
* Updates node-jose to 0.11.1
* Update redux to 4.0.0
> update node-jose and lockbox-datastore to latest

- .gitignore
- .travis.yml
- requirements/tests.txt
- src/webextension/list/containers/item-filter.js
- src/webextension/list/manage/components/account-summary.js
- src/webextension/locales/en-US/list.ftl
- src/webextension/locales/en-US/widgets.ftl
- src/webextension/widgets/panel.js
- test/integration/conftest.py
- test/integration/pages/home.py
- test/integration/tests/test_accessibility.py
- test/integration/tests/test_doorhanger.py
- test/integration/tests/test_guest_mode.py
- test/unit/widgets/panel-test.js
- tox.ini
This expands upon #689 by fixing our failing accessibility tests. Thankfully, these fixes were pretty easy!
> Add accessibility tests

- package-lock.json
- package.json
> chore(package): update webpack-cli to version 3.1.0

- package-lock.json
- package.json
To satisfy some `npm audit` findings
> Upgrade to karma 3.0.0
